# Generated by Django 3.1 on 2021-06-25 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.IntegerField()),
                ('first_val', models.CharField(choices=[('G', 'Good'), ('P', 'Process'), ('B', 'Bad')], default='P', max_length=2)),
                ('second_val', models.CharField(choices=[('G', 'Good'), ('P', 'Process'), ('B', 'Bad')], default='P', max_length=2)),
                ('third_val', models.CharField(choices=[('G', 'Good'), ('P', 'Process'), ('B', 'Bad')], default='P', max_length=2)),
                ('state', models.CharField(choices=[('G', 'Good'), ('P', 'Process'), ('B', 'Bad')], default='P', max_length=2)),
                ('date_upload', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(default='6-2021', max_length=8)),
                ('state', models.CharField(default='G', max_length=2)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.afiliado')),
            ],
        ),
    ]
