# Generated by Django 3.2 on 2021-05-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210429_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afiliado',
            name='state',
        ),
        migrations.AddField(
            model_name='afiliado',
            name='date_look',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='period',
            field=models.CharField(default='6-2021', max_length=16),
        ),
    ]
