# Generated by Django 3.2 on 2021-05-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210506_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliado',
            name='first_val',
            field=models.CharField(choices=[('G', 'Good'), ('P', 'Process'), ('B', 'Bad')], default='P', max_length=2),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='second_val',
            field=models.CharField(choices=[('G', 'Good'), ('P', 'Process'), ('B', 'Bad')], default='P', max_length=2),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='state',
            field=models.CharField(choices=[('G', 'Good'), ('P', 'Process'), ('B', 'Bad')], default='P', max_length=2),
        ),
    ]
