# Generated by Django 3.2 on 2021-05-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210506_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='afiliado',
            old_name='date_look',
            new_name='date_upload',
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='period',
            field=models.CharField(default='6-2021', max_length=8),
        ),
    ]
