# Generated by Django 3.2 on 2021-05-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210506_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afiliado',
            name='period',
        ),
        migrations.AddField(
            model_name='afiliado',
            name='third_val',
            field=models.CharField(choices=[('G', 'Good'), ('P', 'Process'), ('B', 'Bad')], default='P', max_length=2),
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(default='6-2021', max_length=8)),
                ('person', models.ManyToManyField(blank=True, related_name='Afiliados', to='users.Afiliado')),
            ],
        ),
    ]
