# Generated by Django 3.2 on 2021-05-07 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210507_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='person',
        ),
        migrations.AddField(
            model_name='period',
            name='person',
            field=models.ForeignKey(default=1000931454, on_delete=django.db.models.deletion.CASCADE, to='users.afiliado'),
            preserve_default=False,
        ),
    ]
