# Generated by Django 3.1 on 2021-05-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210507_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='state',
            field=models.CharField(default='G', max_length=2),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='period',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
